### PR TITLE
Correct audit classesLevels query param

### PR DESCRIPTION
**Pull request by DMahoney0**
This pull request corrects the audit classesLevels query param to match implemented code.

### CODE REVIEW

**Comment by DMahoney0** [comment]
v2: https://62-148663593-gh.circle-artifacts.com/0/site-preview/api/v2/index.html
v3: https://62-148663593-gh.circle-artifacts.com/0/site-preview/api/v3/index.html

**Review by musicfuel — COMMENTED** [review]
Git does a fairly awful job with rendering the changes here. Looking at `v3` in both the preview and the raw I see `classesLevels` and not `classLevels`. Is that expected for v3 (meaning we intend to change it in v4)?

**Comment by DMahoney0** [comment]
> Git does a fairly awful job with rendering the changes here. Looking at `v3` in both the preview and the raw I see `classesLevels` and not `classLevels`. Is that expected for v3 (meaning we intend to change it in v4)?

You could also use the links I posted above for the actual rendering. I will replay to this internally.

**Comment by DMahoney0** [comment]
> Git does a fairly awful job with rendering the changes here. Looking at `v3` in both the preview and the raw I see `classesLevels` and not `classLevels`. Is that expected for v3 (meaning we intend to change it in v4)?

**Review by musicfuel — APPROVED** [review]

**Pull request merged**
